sudo: false

language: cpp

os:
  - linux
#  - osx

compiler:
  - clang
  #- gcc

addons:
  apt:
    sources:
#      - boost-latest
      #- ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.6
    packages:
      #- g++-4.9
#      - clang-3.6
#      - libboost-system1.55-dev

script:
  # Debug
  - date ; uname -a ; pwd ; ls -l ..; echo $HOSTNAME $USER
  - mkdir /tmp/testWDT
  - df -h /tmp/testWDT
  - cat /etc/fstab
  - ulimit -a

before_install:
  - echo "Travis os name $TRAVIS_OS_NAME"
  #- source ./travis_${TRAVIS_OS_NAME}.sh

language: cpp

