sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
#      - boost-latest
      #- ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.6
    packages:
      #- g++-4.9
#      - clang-3.6
#      - libboost-system1.55-dev
      - openssl
      - libssl-dev

script:
  # Debug
  - date ; uname -a ; pwd ; ls -l ..; echo $HOSTNAME $USER
  - which openssl
  - openssl version -a
  - nc -6 -l 12345 > /dev/null & echo foo | nc -6 -v ::1 12345
  - dpkg -s openssl
  - dpkg -L openssl
  - ldd `which openssl`
  - dpkg -S  /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#  - dpkg -s libssl
#  - dpkg -L libssl
  - dpkg -l | grep ssl

before_install:
  - echo "Travis os name $TRAVIS_OS_NAME"
  #- source ./travis_${TRAVIS_OS_NAME}.sh

language: cpp

